/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NOISE_PB_H_INCLUDED
#define PB_NOISE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Record {
    uint32_t seq_no;
    pb_byte_t bands[31];
    uint32_t laeq_1s;
    uint32_t lceq_1s;
    uint32_t lafmax_1s;
    uint32_t lcfmax_1s;
    uint32_t lcpeak_1s;
} Record;

typedef struct _NoiseRecording {
    int32_t calibration_offset_db_x100;
    pb_size_t records_count;
    Record records[60];
} NoiseRecording;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Record_init_default                      {0, {0}, 0, 0, 0, 0, 0}
#define NoiseRecording_init_default              {0, 0, {Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default, Record_init_default}}
#define Record_init_zero                         {0, {0}, 0, 0, 0, 0, 0}
#define NoiseRecording_init_zero                 {0, 0, {Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero, Record_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Record_seq_no_tag                        1
#define Record_bands_tag                         2
#define Record_laeq_1s_tag                       3
#define Record_lceq_1s_tag                       4
#define Record_lafmax_1s_tag                     5
#define Record_lcfmax_1s_tag                     6
#define Record_lcpeak_1s_tag                     7
#define NoiseRecording_calibration_offset_db_x100_tag 1
#define NoiseRecording_records_tag               2

/* Struct field encoding specification for nanopb */
#define Record_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_no,            1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, bands,             2) \
X(a, STATIC,   SINGULAR, UINT32,   laeq_1s,           3) \
X(a, STATIC,   SINGULAR, UINT32,   lceq_1s,           4) \
X(a, STATIC,   SINGULAR, UINT32,   lafmax_1s,         5) \
X(a, STATIC,   SINGULAR, UINT32,   lcfmax_1s,         6) \
X(a, STATIC,   SINGULAR, UINT32,   lcpeak_1s,         7)
#define Record_CALLBACK NULL
#define Record_DEFAULT NULL

#define NoiseRecording_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   calibration_offset_db_x100,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  records,           2)
#define NoiseRecording_CALLBACK NULL
#define NoiseRecording_DEFAULT NULL
#define NoiseRecording_records_MSGTYPE Record

extern const pb_msgdesc_t Record_msg;
extern const pb_msgdesc_t NoiseRecording_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Record_fields &Record_msg
#define NoiseRecording_fields &NoiseRecording_msg

/* Maximum encoded size of messages (where known) */
#define NOISE_PB_H_MAX_SIZE                      NoiseRecording_size
#define NoiseRecording_size                      4266
#define Record_size                              69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
