/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "noise.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NoiseRecording, NoiseRecording, 4)


PB_BIND(NoiseRecording_Record, NoiseRecording_Record, AUTO)



