/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NOISE_PB_H_INCLUDED
#define PB_NOISE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _NoiseRecording {
    uint32_t seq_no;
    pb_byte_t bands[31];
    uint8_t laeq;
    uint8_t lceq;
    uint8_t lafmax;
    uint8_t lcfmax;
    uint8_t lcpeak;
    uint8_t record_interval_seconds;
    bool has_battery_mv;
    uint16_t battery_mv;
    bool has_laeq_5m;
    uint8_t laeq_5m;
    bool has_lceq_5m;
    uint8_t lceq_5m;
    bool has_laeq_30m;
    uint8_t laeq_30m;
    bool has_lceq_30m;
    uint8_t lceq_30m;
} NoiseRecording;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define NoiseRecording_init_default              {0, {0}, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define NoiseRecording_init_zero                 {0, {0}, 0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define NoiseRecording_seq_no_tag                1
#define NoiseRecording_bands_tag                 2
#define NoiseRecording_laeq_tag                  3
#define NoiseRecording_lceq_tag                  4
#define NoiseRecording_lafmax_tag                5
#define NoiseRecording_lcfmax_tag                6
#define NoiseRecording_lcpeak_tag                7
#define NoiseRecording_record_interval_seconds_tag 8
#define NoiseRecording_battery_mv_tag            9
#define NoiseRecording_laeq_5m_tag               10
#define NoiseRecording_lceq_5m_tag               11
#define NoiseRecording_laeq_30m_tag              12
#define NoiseRecording_lceq_30m_tag              13

/* Struct field encoding specification for nanopb */
#define NoiseRecording_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_no,            1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, bands,             2) \
X(a, STATIC,   SINGULAR, UINT32,   laeq,              3) \
X(a, STATIC,   SINGULAR, UINT32,   lceq,              4) \
X(a, STATIC,   SINGULAR, UINT32,   lafmax,            5) \
X(a, STATIC,   SINGULAR, UINT32,   lcfmax,            6) \
X(a, STATIC,   SINGULAR, UINT32,   lcpeak,            7) \
X(a, STATIC,   SINGULAR, UINT32,   record_interval_seconds,   8) \
X(a, STATIC,   OPTIONAL, UINT32,   battery_mv,        9) \
X(a, STATIC,   OPTIONAL, UINT32,   laeq_5m,          10) \
X(a, STATIC,   OPTIONAL, UINT32,   lceq_5m,          11) \
X(a, STATIC,   OPTIONAL, UINT32,   laeq_30m,         12) \
X(a, STATIC,   OPTIONAL, UINT32,   lceq_30m,         13)
#define NoiseRecording_CALLBACK NULL
#define NoiseRecording_DEFAULT NULL

extern const pb_msgdesc_t NoiseRecording_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define NoiseRecording_fields &NoiseRecording_msg

/* Maximum encoded size of messages (where known) */
#define NOISE_PB_H_MAX_SIZE                      NoiseRecording_size
#define NoiseRecording_size                      73

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
